# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 11:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0003_auto_20161013_0657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translations',
            name='session',
        ),
    ]
